export const DEFAULT_SLOTS = [
  "Waifu",
  "Husbando",
  "Not Human",
  "Not Alive or Artificial",
  "Old",
  "Minor Character",
  "Evil",
  "Child",
  "Comic Relief",
  "Wildcard",
];

export const CATEGORY_POOL = [
  "Secretly OP",
  "Stylish",
  "Good smile",
  "Good drip",
  "Good cook",
  "Needs therapy",
  "Chaotic good",
  "Edgelord",
  "Mentor",
  "Rival",
  "Likely to betray the party",
  "Likely to save the world",
  "Crybaby",
  "Punchable",
  "Underrated",
  "Overrated but lovable",
  "Transformation",
  "Catchphrase",
  "Cool weapon",
  "Starts bar fights",
  "Ends bar fights",
  "Himbo",
  "Dumbass",
  "Smart",
  "Badass mom",
  "Badass dad",
  "Tragic backstory",
  "Glow-up",
  "Terrifying if real",
  "Would pet the dog",
  "Should touch grass",
  "Zero riz",
  "Maximum riz",
  "Villain redemption",
  "Should’ve stayed evil",
  "Gets isekai’d",
  "Idol material",
  "Good ship with anyone",
  "Cool power system user",
  "Meme-able",
  "Wingman",
  "Sleeps through the apocalypse",
  "Needs to be stopped",
  "Quotable",
  "Iconic scream",
  "Iconic laugh",
  "Cool eyes",
  "Cool voice",
  "Runs a cult",
  "Wins a Nobel Prize",
  "Pilot",
  "Swordsman",
  "Gun user",
  "Magic user",
  "Healer",
  "Support character",
  "Bad decision-maker",
  "Loyal",
  "Betrayed",
  "Bad roommate",
  "Good roommate",
  "Animal companion",
  "Rage quitter",
  "Makes friends with a rock",
  "Unsafe with technology",
  "Unsafe with children",
  "Group project leader",
  "Ghosts you",
  "Weird hobby",
  "Good music taste",
  "Bad music taste",
  "Fashion-challenged",
  "Battle theme (character-based)",
  "Unhinged",
  "Based",
  "Feral",
  "Survives a horror movie",
  "Dies first in a horror movie",
  "Good design",
  "Bad design",
  "Cool armor",
  "Cool mount",
  "Chef",
  "Bad chef",
  "Saves Christmas",
  "Dramatic",
  "Chill",
  "Playful",
  "Stoic",
  "Big brother",
  "Big sister",
  "Younger brother",
  "Younger sister",
  "Forgets birthdays",
  "Remembers birthdays",
  "Comeback artist",
  "Bad luck",
  "Good luck",
  // Kept from previous list (non-conflicting)
  "Deserves a Spin-off",
  "Overpowered but Lazy",
  "Unintentionally Hilarious",
  "Only Has One Outfit",
  "Defies Physics",
  "Breaking the Fourth Wall",
  "Plot Armor Heavy",
  "Cinnamon Roll",
  "Chaotic Evil",
  "Lawful Stupid",
  "Always Hungry",
  "Always Sleepy",
  "Rich but Humble",
  "Poor but Happy",
  "Bad with Directions",
  "Weapon of Mass Destruction",
  "Gentle Giant",
  "Small but Mighty",
  "Glasses Character",
  "Tsundere (Classic)",
  "Yandere (Scary)",
  "Dandere (Shy)",
  "Kuudere (Cool)",
  "Genki Girl/Boy",
  "Chuunibyou",
  "Harem Protagonist",
  "Reverse Harem Protagonist",
  "Butler/Maid",
  "Teacher",
  "Student Council President",
  "Delinquent",
  "Transfer Student",
  "Childhood Friend",
  "Mascot Character",
  "Non-Human Sidekick",
  "Talking Animal",
  "Spirit/Yokai",
  "God/Goddess",
  "Demon/Devil",
  "Angel",
  "Cyborg/Android",
  "Alien",
  "Time Traveler",
  "Ghost",
  "Vampire",
  "Werewolf",
  "Zombie",
  "Dragon",
  "Mermaid/Merman",
  "Fairy/Elf",
  "Witch/Wizard",
  "Ninja/Assassin",
  "Pirate",
  "Thief/Rogue",
  "Scientist/Inventor",
  "Musician/Bard",
  "Artist",
  "Athlete",
  "Gamer/Otaku",
  "NEET",
  "Salaryman/Office Lady",
];
