export const POKEMON_DEFAULT_SLOTS = [
  "Little Guy",
  "Bird",
  "Dragon",
  "Water Type",
  "Ghost / Dark",
  "Starter",
  "Legendary",
  "Competitively Strong",
  "Adorable",
  "Wildcard",
];

export const POKEMON_CATEGORY_POOL = [
  // Vibes & Aesthetics
  "Little Guy",
  "Big Boy",
  "Absolute Unit",
  "Elegant",
  "Terrifying",
  "Adorable",
  "Ugly but Lovable",
  "Best Shiny",
  "Worst Shiny",
  "Great Design",
  "Chaotic Energy",
  "Chill Vibes",
  "Mysterious",
  "Silly",
  "Dramatic",
  "Edgy",
  "Wholesome",
  "Spooky",

  // Physical Traits
  "Bird",
  "No Legs",
  "Four Legs",
  "Snake / Worm",
  "Floaty",
  "Spiky",
  "Round",
  "Long Boy",
  "Has a Face on It That Shouldn't Have a Face",

  // Type Categories
  "Fire Type",
  "Water Type",
  "Grass Type",
  "Electric Type",
  "Psychic Type",
  "Dragon",
  "Ghost / Dark",
  "Fairy",
  "Steel",
  "Ice Type",
  "Fighting Type",
  "Poison Type",
  "Bug",
  "Rock / Ground",

  // Battle & Competitive
  "Competitively Strong",
  "Comptetively Cursed (Terrible in battle)",
  "One-Shot Wonder",
  "The Tank",
  "Speed Demon",
  "Special Attacker",
  "Setup Sweeper",
  "Pivot / Utility",
  "Gimmick that Actually Works",
  "Gimmick that Does Not Work",
  "Would Destroy You in a Real Fight",
  "Could NOT beat you in a fight",
  "Banned from Ranked",

  // Origins & Lore
  "Starter",
  "Legendary",
  "Mythical",
  "Pseudo-Legendary",
  "Fossil Pokemon",
  "Baby Pokemon",
  "Regional Form",
  "Has a Mega Evolution",
  "Has a Gigantamax Form",
  "Gen 1 Classic",
  "Deep Cut (Obscure Pick)",
  "Trade Evolution",
  "Evolution Stone User",
  "Friendship Evolution",
  "Early Route Pokemon (Commonly found in the first area)",
  "Final Boss Energy",

  // Viability & Culture
  "Underrated",
  "Overused but Still Beloved",
  "Meme-able",
  "Iconic Cry",
  "Mascot Material",
  "Would Make a Great Pet",
  "Would NOT Make a Great Pet",
  "Could Run a Business",
  "Would Survive in the Wild",
  "Needs Constant Care",
  "Starter Eeveelution (or should be)",
  "Main Character Energy",
  "Sidekick Energy",
  "Villain Energy",
  "Comic Relief",
  "Gym Leader Worthy",
  "Champion Worthy",
  "Evil Team Vibes",

  // Type Combos & Traits
  "Unique Type Combo",
  "Pure Monotype",
  "Dual Type Powerhouse",
  "Defensive Wall",
  "Would Be a Good Legendary Box Art",
  "Literally Just a Rock",
  "Literally Just Food",
  "Based on a Real Animal",
  "Based on a Myth / Legend",
  "Based on an Object",
  "The Regional Rodent",
  "The Regional Bug",
  "The Early Bird",

  // Personality / Headcanon
  "Chaotic Good",
  "Lawful Good",
  "Chaotic Evil",
  "Loyal to a Fault",
  "Would Betray You for a Berry",
  "The Gentle Giant",
  "Feral",
  "Could Run a Cult",
  "Fashion Icon",
  "Bad at Its Own Typing",
  "Hits Different in a Nuzlocke",
  "Unexpectedly Terrifying if Real",
  "Would Be a Great Plushie",
  "Fan Favorite from a Bad Game",
];
