export const POKEMON_DEFAULT_SLOTS = [
  "Little Guy",
  "Bird",
  "Dragon",
  "Water Type",
  "Ghost / Dark",
  "Starter",
  "Legendary",
  "Competitively Strong",
  "Adorable",
  "Wildcard",
];

export const POKEMON_CATEGORY_POOL = [
  // Vibes & Aesthetics
  "Little Guy",
  "Chonker",
  "Absolute Unit",
  "Elegant",
  "Terrifying",
  "Adorable",
  "Ugly but Lovable",
  "Best Shiny",
  "Worst Shiny",
  "Great Design",
  "Chaotic Energy",
  "Chill Vibes",
  "Mysterious",
  "Silly",
  "Dramatic",
  "Edgy",
  "Wholesome",
  "Spooky",
  "Fugly",

  // Physical Traits
  "Bird",
  "No Legs",
  "Four Legs",
  "Snake / Worm",
  "Floaty",
  "Spiky",
  "Round",
  "Long Boy",
  "Stupid Face",

  // Type Categories
  "Fire Type",
  "Water Type",
  "Grass Type",
  "Electric Type",
  "Psychic Type",
  "Dragon",
  "Ghost / Dark",
  "Fairy",
  "Steel",
  "Ice Type",
  "Fighting Type",
  "Poison Type",
  "Bug",
  "Rock / Ground",

  // Battle & Competitive
  "Competitively Strong",
  "Terrible in battle",
  "Would",
  "The Tank",
  "Speed Demon",
  "Special Attacker",
  "Setup Sweeper",
  "Pivot / Utility",
  "Gimmick that Actually Works",
  "Gimmick that Does Not Work",
  "Would Destroy You in a Real Fight",
  "Could NOT beat you in a fight",
  "Banned from Ranked",

  // Origins & Lore
  "Starter",
  "Legendary",
  "Mythical",
  "Pseudo-Legendary",
  "Fossil Pokemon",
  "Baby Pokemon",
  "Regional Form",
  "Best Mega Evolution",
  "Best Gigantamax Form",
  "Gen 1 Classic",
  "Deep Cut (Obscure Pick)",
  "Trade Evolution",
  "Evolution Stone User",
  "Friendship Evolution",
  "Early Route Pokemon",
  "Final Boss Energy",

  // Viability & Culture
  "Underrated",
  "Overused but Still Beloved",
  "Meme-able",
  "Iconic Cry",
  "Mascot Material",
  "Would Make a Great Pet",
  "Would NOT Make a Great Pet",
  "Could Run a Business",
  "Would Survive in the Wild",
  "Needs Constant Care",
  "Main Character Energy",
  "Sidekick Energy",
  "Villain Energy",
  "Comic Relief",
  "Gym Leader's Ace",
  "Champion Worthy",
  "Evil Team Vibes",

  // Type Combos & Traits
  "Rare Type Combo",
  "Pure Monotype",
  "Dual Type Powerhouse",
  "Defensive Wall",
  "Good Box Art",
  "Literally Just a Rock",
  "Literally Just Food",
  "Based on a Real Animal",
  "Based on a Myth / Legend",
  "Based on an Object",
  "The Regional Rodent",
  "The Regional Bug",
  "The Early Bird",

  // Personality / Headcanon
  "Chaotic Good",
  "Lawful Good",
  "Chaotic Evil",
  "Loyal to a Fault",
  "Would Betray You for a Berry",
  "The Gentle Giant",
  "Feral",
  "Could Run a Cult",
  "Fashion Icon",
  "Bad at Its Own Typing",
  "Hits Different in a Nuzlocke",
  "Unexpectedly Terrifying if Real",
  "Would Be a Great Plushie",
  "Fan Favorite from a Bad Game",
];
